import { UUID } from "@/util/uuid.js";
const items = [
  {
    id: UUID(),
    text: "South",
    children: [
      { id: 1, gameId: "1", code: "vndTPHCM", text: "胡志明" },
      { id: UUID(), gameId: "2", code: "vndDongThap", text: "同塔" },
      { id: UUID(), gameId: "3", code: "vndCaMau", text: "金瓯" },
      { id: UUID(), gameId: "4", code: "vndBenTre", text: "槟椥" },
      { id: UUID(), gameId: "5", code: "vndVungTau", text: "头顿" },
      { id: UUID(), gameId: "6", code: "vndDongNai", text: "同奈" },
      { id: UUID(), gameId: "7", code: "vndBacLieu", text: "薄辽" },
      { id: UUID(), gameId: "8", code: "vndCanTho", text: "芹苴" },
      { id: UUID(), gameId: "9", code: "vndSocTrang", text: "朔庄" },
      { id: UUID(), gameId: "10", code: "vndTayNinh", text: "西宁" },
      { id: UUID(), gameId: "11", code: "vndAnGiang", text: "安江" },
      { id: UUID(), gameId: "12", code: "vndBinhThuan", text: "平顺" },
      { id: UUID(), gameId: "13", code: "vndVinhLong", text: "永隆" },
      { id: UUID(), gameId: "14", code: "vndBinhDuong", text: "平阳" },
      { id: UUID(), gameId: "15", code: "vndTraVinh", text: "茶荣" },
      { id: UUID(), gameId: "1", code: "vndTPHCM", text: "胡志明" },
      { id: UUID(), gameId: "16", code: "vndLongAn", text: "隆安" },
      { id: UUID(), gameId: "17", code: "vndBinhPhuoc", text: "平福" },
      { id: UUID(), gameId: "18", code: "vndHauGiang", text: "后江" },
      { id: UUID(), gameId: "19", code: "vndTienGiang", text: "前江" },
      { id: UUID(), gameId: "20", code: "vndKienGiang", text: "坚江" },
      { id: UUID(), gameId: "21", code: "vndDaLat", text: "大叻" },
    ],
  },
  {
    id: UUID(),
    text: "central",
    children: [
      { id: UUID(), gameId: "22", code: "vndThuaThien", text: "承天顺化" },
      { id: UUID(), gameId: "23", code: "vndPhuYen", text: "富安" },
      { id: UUID(), gameId: "24", code: "vndQuangNam", text: "广南" },
      { id: UUID(), gameId: "25", code: "vndDakLak", text: "得勒" },
      { id: UUID(), gameId: "26", code: "vndDaNang", text: "岘港" },
      { id: UUID(), gameId: "27", code: "vndKhanhHoa", text: "庆和" },
      { id: UUID(), gameId: "28", code: "vndBinhDinh", text: "平定" },
      { id: UUID(), gameId: "29", code: "vndQuangBinh", text: "广平" },
      { id: UUID(), gameId: "30", code: "vndQuangTri", text: "广治" },
      { id: UUID(), gameId: "31", code: "vndGiaLai", text: "嘉莱" },
      { id: UUID(), gameId: "32", code: "vndNinhThuan", text: "宁顺" },
      { id: UUID(), gameId: "26", code: "vndDaNang", text: "岘港" },
      { id: UUID(), gameId: "33", code: "vndQuangNgai", text: "广义" },
      { id: UUID(), gameId: "34", code: "vndDakNong", text: "多农" },
      { id: UUID(), gameId: "27", code: "vndKhanhHoa", text: "庆和" },
      { id: UUID(), gameId: "35", code: "vndKonTum", text: "昆嵩" },
    ],
  },

  {
    id: UUID(),
    text: "north",
    children: [{ id: UUID(), gameId: "36", code: "vndHanoi", text: "河内" }],
  },
];
export default items;
